### ISSUE TITLE
Надо придумать другое имя, иначе не совсем понятна логика

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW06_Book_Store#13]
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/22a1cc2eb2e5de67fdeb21424fc1f9f1263f28f4/app/lib.py#L75

**Comment by Lagunov-PRO** [comment]
@coursar 
Отказался от идеи разбивать поиск на два отдельных. Сортировка по частоте вхождения справляется прекрасно. Удалил второе имя.
https://github.com/Lagunov-PRO/HW06_Book_Store/commit/3f8ea384d2948c65cae554381577bf174a9bb22b
