### ISSUE TITLE
Попробуйте просто собрать все списки и устранить из них дубли

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW06_Book_Store#2]
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/5e235073bccabaf5ce7b6387c39618b1b542d26e/app/lib.py#L42-L52

Т.е. сделать нечто вроде

```python
all_results = title_search + author_search + tag_search
return remove_duplicates(all_result)
```

И подумайте, как упростить себе жизнь для поиска уникальных объектов?

Подсказка: возможно, стоит добавить какой-то ключик в `dict`

**Comment by Lagunov-PRO** [comment]
@coursar 
Сделал отдельную функцию для проверки дубликатов:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/db7705a5a4dc5dc1cc5111d188a5973e2f4e4d69/app/lib.py#L56-L62

Для упрощения жизни добавляю ключ 'code' равный индексу элемента в списке books, но пока его нигде не применяю:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/db7705a5a4dc5dc1cc5111d188a5973e2f4e4d69/app/lib.py#L11-L13

**Comment by Lagunov-PRO** [comment]
@coursar 
Нашёл применение для 'code'!
Получаем список уникальных кодов из результата поиска:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/62a2f4412568194b98d36f6eec8652d85a938f4e/app/lib.py#L56-L59

Затем из всего списка книг выбираем только книги с этими кодами:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/62a2f4412568194b98d36f6eec8652d85a938f4e/app/lib.py#L62-L69

Соответственно, функция поиска теперь вызывает эти две функции. Читабельность немного потерялась:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/62a2f4412568194b98d36f6eec8652d85a938f4e/app/lib.py#L53

**Comment by Lagunov-PRO** [comment]
@coursar 
Пошёл дальше и реализовал сортировку результата поиска по частоте вхождения:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/a22cf81e18cac31ab23a097011c66df9656f5ed6/app/lib.py#L73-L90
 
Мне кажется, должен быть способ проще, без создания промежуточного словаря. Подскажете?

**Comment by Lagunov-PRO** [comment]
Нашёл способ гораздо проще:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/c880b4648494763a95b628b03f055152df1006a9/app/lib.py#L97-L111

**Comment by coursar** [comment]
ok ))
