### ISSUE TITLE
Посмотрите вывод пагинации и навигацию по тегам

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW06_Book_Store#29]
На этой неделе был занят только тестовыми заданиями, поэтому до конца не доделано.
Ну и про мой парсер тегов с литреса вы ничего не сказали ))

**Comment by coursar** [comment]
Про пагинацию отписался.

**Comment by coursar** [comment]
А так всё круто, здорово, что так развиваетесь
