### ISSUE TITLE
Чем отличаются эти три функции?

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW06_Book_Store#3]
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/5e235073bccabaf5ce7b6387c39618b1b542d26e/app/lib.py#L55-L82

Возможно ли сделать так, чтобы они занимали меньше места?

**Comment by Lagunov-PRO** [comment]
@coursar 
Они отличаются только ключами словарей проверяемых значений. Объединил в одну функцию, но так как теги у нас хранятся в списке, к ним нельзя применять метод .lower(), поэтому ввёл проверку на тип данных:
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/db7705a5a4dc5dc1cc5111d188a5973e2f4e4d69/app/lib.py#L65-L75

**Comment by coursar** [comment]
Тогда уж стоило сделать и проверку на список ))
