### ISSUE TITLE
Попробуйте преобразовать в чистую функцию

### ISSUE THREAD

**Issue by coursar** [Lagunov-PRO/HW06_Book_Store#8]
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/22a1cc2eb2e5de67fdeb21424fc1f9f1263f28f4/app/lib.py#L19-L24

В качестве доп.задания

**Comment by Lagunov-PRO** [comment]
@coursar Попробовал!
Насколько я понимаю, чистая функция не должна ничего делать с передаваемыми ей параметрами и объектами. Поэтому создаём новый контейнер. А чтобы не перекладывать новый контейнер в ещё более новый, принимаем на вход все книги сразу.

https://github.com/Lagunov-PRO/HW06_Book_Store/blob/68b3fd2d8efea63a874c9a278525cfa50f369f6b/app/lib.py#L20-L28

Не уверен в решении, поэтому не закрываю.

**Comment by Lagunov-PRO** [comment]
@coursar 
Ошибка предыдущего решения в том, что я не создавал новый контейнер, а просто ссылался новым именем на старый.
Исправленное решение (уже после занятия, так что не считается, конечно):
https://github.com/Lagunov-PRO/HW06_Book_Store/commit/9f1f79bc10065186d62b28c905653e6fdc100e2c#diff-d2a57dc1d883fd21fb9951699df71cc7
https://github.com/Lagunov-PRO/HW06_Book_Store/blob/1c8638945226032dbd819dd2821d23850c5f0ec1/app/lib.py#L23-L30
